# Generated by Django 2.1.7 on 2019-03-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('transaction_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('fiat_currency', models.CharField(max_length=3)),
                ('crypto_address', models.CharField(max_length=30)),
                ('success_boolean', models.BooleanField()),
            ],
        ),
    ]
