# Generated by Django 2.1.7 on 2019-03-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposit', '0002_delete_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositModel',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('success_boolean', models.BooleanField()),
                ('amount', models.IntegerField()),
                ('fiat_Currency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('tnd', 'TND')], default='USD', max_length=3)),
                ('Crypto_Address', models.CharField(max_length=35)),
            ],
        ),
    ]
