# Generated by Django 2.1.7 on 2019-03-27 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0007_depositmodel_crypto_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositmodel',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
