# Generated by Django 2.1.7 on 2019-03-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0009_auto_20190327_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositmodel',
            name='crupto_amout',
            field=models.FloatField(default=0.0),
        ),
    ]
