# Generated by Django 2.1.7 on 2019-03-27 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0010_depositmodel_crupto_amout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositmodel',
            old_name='crupto_amout',
            new_name='crypto_amout',
        ),
    ]
