# Generated by Django 2.1.7 on 2019-03-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0011_auto_20190327_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositmodel',
            name='custom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depositmodel',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositmodel',
            name='crypto_amout',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositmodel',
            name='success_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
