# Generated by Django 2.1.7 on 2019-03-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0012_auto_20190327_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositmodel',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='depositmodel',
            name='custom',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
