# Generated by Django 2.1.7 on 2019-03-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0013_auto_20190327_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositmodel',
            name='transaction_id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='depositmodel',
            name='custom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
