# Generated by Django 2.1.7 on 2019-03-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0015_auto_20190327_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositmodel',
            name='custom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
