# Generated by Django 2.1.7 on 2019-03-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0016_auto_20190327_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositmodel',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
