# Generated by Django 2.1.7 on 2019-03-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0017_auto_20190330_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositmodel',
            old_name='crypto_amout',
            new_name='crypto_amount',
        ),
    ]
