"""
Django settings for DexWebSite project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ssihyr^e=xdx5i1^1(ih%(%)d3(g1*kb!dyq9fq_vp&f@blb2x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_URL_NGROK = '127.0.0.1:8000'


ALLOWED_HOSTS = [ALLOWED_URL_NGROK,'127.0.0.1','localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'deposit',
    'registration',
    'paypal.standard.ipn',
    'django_celery_results',
    'corsheaders',



]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = False

CORS_ORIGIN_WHITELIST = (
    '127.0.0.1:8000'
    'localhost:8000',
    '127.0.0.1:9000'
)


CORS_ALLOW_METHODS = (

    'GET',
    'POST',

)


ROOT_URLCONF = 'DexWebSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DexWebSite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Email configurations
EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com' # Set your email host
EMAIL_PORT=587
EMAIL_HOST_USER='mdiniblockchain@gmail.com'
EMAIL_HOST_PASSWORD='utopie1990' #Your password
EMAIL_USE_TLS=True
DEFAULT_FROM_EMAIL = 'mdiniblockchain@gmail.com'

#Cripsy form
CRISPY_TEMPLATE_PACK = 'bootstrap4'


#Registration configs
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# celery
CELERY_BROKER_URL = 'amqp://guest:guest@127.0.0.1:5672//'

# CELERY_RESULT_BACKEND = 'django-db'
CELERY_RESULT_BACKEND = 'amqp://guest:guest@127.0.0.1:5672//'

# CELERY_IMPORTS = ("DexWebSite.tasks", )


CELERY_TASK_RESULT_EXPIRES = 18000  # 5 hours.
# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# stripe api config
STRIPE_SECRET_KEY = 'sk_test_rSJxnosKH4orBxb88lk7PwqJ'
STRIPE_PUBLISHABLE_KEY = 'pk_test_OFGy9zNfKzZsl93BgfBXva6H'

# binance api config
BINANCE_SECRET_KEY = '41srG16MW2Exwh3RXVytaXsMNcpZsT7VfcmaIrhhlaNJLOKWFTDMlZPUGle5JDBd'
BINANCE_PUBLISHABLE_KEY = 'N6t1AZvVX9SJ8bBxeOyBnGwUVJZCMHyixnOM4WZcdcz7ISbo2VkCmlBkKonPpvEa'

# coinapi api config
COINAPI_KEY = '6A0EBE25-F264-4238-8DC9-23D19542DF67'

# coinbase api config
COINBASE_API_KEY = 'vnFfW3kq1R3MpC81'
COINBASE_API_SECRET = 'VdHevQp9hwmUMHtrBZdMM6cXYVkNPsmV'

# coin market cap api config
COIN_MARKET_CAP_KEY = 'd8ecdcf0-640b-4dbe-8cd5-7254ad46a318'

# Paypal Api
PAYPAL_USERNAME = 'mdiniblockchain_api1.gmail.com'
PAYPAL_PASSWORD = 'RFVJ49WMG4P8XTM8'
PAYPAL_RECEIVER_EMAIL = 'mdiniblockchain@gmail.com'
PAYPAL_CLIENT_ID = 'AaKK3r7pNIypoohGXGhmmnv0RYvvVERIWpFpy4lbCU19ZptKea1M82cH21vgdJ4-Vudppy6tanFTSgip'
PAYPAL_SECRET = 'EEw1cZbDjeuOtrtUDcf_UyxbKa2k1i9Xs7ycSWsJ-McReGfQHoyIReMqOjoy8TIyO2m1gGaGqIuEvVAE'
PAYPAL_SIGNATURE = 'A9J3rV4Yoys9FC3qB3nIqi7poEhpAXEOC2UeHIqY5fNaVvMW60CW7WHk'
# for test
PAYPAL_TEST = True

# braintree api config
BRAINTREE_MERCHANT_ID = "kj6gqc6kk3xvnmy8"
BRAINTREE_PUBLIC_KEY = "wx46sqk5jtxkjtzg"
BRAINTREE_PRIVATE_KEY = "72bd9b8624a274615dc3130b8b82e974"

